# Generated by Django 2.0 on 2018-01-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=12, verbose_name='课程名')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(max_length=10, verbose_name='班级')),
                ('gMaxNum', models.IntegerField(default=50, verbose_name='班级最大人数')),
                ('gCurNum', models.IntegerField(default=0, verbose_name='当前人数')),
                ('gCourse', models.ManyToManyField(to='tmms.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mSNum', models.CharField(max_length=10, unique=True, verbose_name='书号')),
                ('mName', models.CharField(max_length=20, verbose_name='书名')),
                ('mCurCount', models.IntegerField(default=0, verbose_name='当前数量')),
                ('mMaxCount', models.IntegerField(default=50, verbose_name='最大库存')),
                ('mMinCount', models.IntegerField(default=0, verbose_name='最小库存')),
                ('mPrice', models.IntegerField(blank=True, verbose_name='价格')),
            ],
            options={
                'verbose_name': '教学材料',
                'verbose_name_plural': '教学材料',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nType', models.IntegerField(default=0, verbose_name='类型')),
                ('nDate', models.DateField(verbose_name='时间')),
                ('nCount', models.IntegerField(verbose_name='数量')),
                ('nMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmms.Material', verbose_name='教学材料')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('sName', models.CharField(max_length=10, verbose_name='姓名')),
                ('sAge', models.IntegerField(blank=True, verbose_name='年龄')),
                ('sHobby', models.CharField(blank=True, max_length=200, verbose_name='爱好')),
                ('sOther', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('sGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmms.Grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=12, verbose_name='姓名')),
                ('tAge', models.IntegerField(blank=True, verbose_name='年龄')),
                ('tOther', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('tGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmms.Grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cMaterials',
            field=models.ManyToManyField(to='tmms.Material', verbose_name='教学材料'),
        ),
    ]
